markdown_extensions:
- pymdownx.tilde: null
- pymdownx.highlight:
    linenums: false
- pymdownx.superfences
nav:
- Rust:
  - rust/maxflow.md
  - rust/util.md
  - rust/convolution.md
  - rust/bisect.md
  - rust/segtree.md
  - rust/lazy_segtree.md
  - Math:
    - rust/math/pow_mod.md
    - rust/math/integer.md
site_name: My Docs
theme:
  language: ja
  name: material
