name: Deploy Doc
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: local-fix
      #   run: |
      #     # Hack to get setup-python to work on act
      #     # (see https://github.com/nektos/act/issues/251)
      #     # Hack to get setup-python to work on act
      #     if [ ! -f "/etc/lsb-release" ] ; then
      #       echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
      #     fi

      - name: setup python env
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: install dependencies
        working-directory: ./tools/docs_generator
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: generate files for mkdocs
        working-directory: ./tools/docs_generator/generator
        run: |
          python main.py ../../../rust_libs/
          # python main.py ../../../py_libs/
          # python main.py ../../../py_typicals/

      - name: mkdocs build
        working-directory: ./tools/docs_generator/docs
        run: |
           mkdocs build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./tools/docs_generator/docs/site